#!/bin/bash
currentmp3=$(readlink -f /proc/$(printf "%u" `ps -C mpg321 o pid=`)/fd/3) && echo $currentmp3 > /tmp/lastmp3 && if [ ! -d "/tmp/mp3rejects" ]; then mkdir /tmp/mp3rejects ;fi && mv $currentmp3 /tmp/mp3rejects && killall -2 mpg321

#currentmp3=$(i=$(printf "%u" `ps -C mpg321 o pid=`) && ls -al /proc/$i/fd/3 | rev | echo `cut -d " " -f -1` | rev ) && echo $currentmp3 > /tmp/lastmp3 && if [ ! -d "/tmp/mp3rejects" ]; then mkdir /tmp/mp3rejects ;fi && mv $currentmp3 /tmp/mp3rejects && killall -2 mpg321

#currentmp3=$(i=$(printf "%u" `ps ho %p -C mpg321`) && ls -al /proc/$i/fd/3 | rev | echo `cut -d " " -f -1` | rev ) && echo $currentmp3 > /tmp/lastmp3 && if [ ! -d "/tmp/mp3rejects" ]; then mkdir /tmp/mp3rejects ;fi && mv $currentmp3 /tmp/mp3rejects && killall -2 mpg321
